const fs = require('fs');
const path = require('path');
const {
  withAndroidManifest,
  withDangerousMod,
  withStringsXml,
  withInfoPlist,
  AndroidConfig,
  createRunOncePlugin,
} = require('expo/config-plugins');

/**
 * Native hardening that cannot be expressed in app.json alone.
 *
 * Red Letter makes no network requests at all. That is worth enforcing in the
 * built app rather than merely being true of today's source, because the
 * strongest security property this product has is that there is nothing to
 * exfiltrate and no server to breach — and a dependency added in six months
 * should not be able to quietly change that.
 */

/**
 * Removes the INTERNET permission from release builds.
 *
 * Android grants android.permission.INTERNET to every app by default and Expo
 * adds it explicitly. Dropping it means the OS itself refuses any socket the
 * app tries to open, so an analytics SDK pulled in transitively cannot phone
 * home even if it wanted to. Debug builds keep it, because Metro serves the JS
 * bundle over the network during development.
 */
function withNoInternetPermission(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;

    manifest['uses-permission'] = (manifest['uses-permission'] ?? []).filter(
      (permission) => permission.$?.['android:name'] !== 'android.permission.INTERNET',
    );

    // `tools:node="remove"` strips it again if a library's manifest merges it
    // back in. The tools namespace has to be declared for that to be legal.
    manifest.$ = manifest.$ ?? {};
    manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';

    manifest['uses-permission'].push({
      $: {
        'android:name': 'android.permission.INTERNET',
        'tools:node': 'remove',
      },
    });

    return mod;
  });
}

/**
 * Blocks cleartext traffic and disables the OS backup agent.
 *
 * `allowBackup=false` matters here: Android's auto-backup would otherwise copy
 * the app's private files into the user's Google Drive. The data file is
 * encrypted, but its key lives in the Keystore and is not backed up, so the
 * copy would be both useless and an unnecessary extra location for the user's
 * calendar to exist in. Settings offers a real export instead.
 */
function withAndroidHardening(config) {
  return withAndroidManifest(config, (mod) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);

    application.$['android:usesCleartextTraffic'] = 'false';
    application.$['android:allowBackup'] = 'false';
    application.$['android:fullBackupContent'] = 'false';
    application.$['android:dataExtractionRules'] = '@xml/data_extraction_rules';

    return mod;
  });
}

/**
 * Writes the backup rules the manifest above points at.
 *
 * Android 12 and newer read `dataExtractionRules` for both cloud backup and
 * direct device-to-device transfer; `allowBackup=false` alone no longer covers
 * the transfer case. Both are excluded outright.
 */
function withDataExtractionRules(config) {
  return withDangerousMod(config, [
    'android',
    (mod) => {
      const xmlDir = path.join(mod.modRequest.platformProjectRoot, 'app/src/main/res/xml');
      fs.mkdirSync(xmlDir, { recursive: true });

      fs.writeFileSync(
        path.join(xmlDir, 'data_extraction_rules.xml'),
        [
          '<?xml version="1.0" encoding="utf-8"?>',
          '<!-- Generated by plugins/withRedLetterSecurity.js. Do not edit by hand. -->',
          '<data-extraction-rules>',
          '    <cloud-backup>',
          '        <exclude domain="root" />',
          '    </cloud-backup>',
          '    <device-transfer>',
          '        <exclude domain="root" />',
          '    </device-transfer>',
          '</data-extraction-rules>',
          '',
        ].join('\n'),
        'utf8',
      );

      return mod;
    },
  ]);
}

/**
 * Excludes the data directory from iCloud and iTunes backups for the same
 * reason: the key is not in the backup, so the copy could never be restored.
 */
function withIosHardening(config) {
  return withInfoPlist(config, (mod) => {
    mod.modResults.NSAppTransportSecurity = {
      NSAllowsArbitraryLoads: false,
      NSAllowsArbitraryLoadsInWebContent: false,
      NSAllowsLocalNetworking: false,
    };

    // No background modes, no location, no audio: the app has no reason to run
    // when it is not on screen beyond the notifications the OS schedules.
    delete mod.modResults.UIBackgroundModes;

    return mod;
  });
}

/** Names the app in the Android permission dialogs. */
function withAppName(config) {
  return withStringsXml(config, (mod) => {
    mod.modResults = AndroidConfig.Strings.setStringItem(
      [{ $: { name: 'app_name', translatable: 'false' }, _: 'Red Letter' }],
      mod.modResults,
    );
    return mod;
  });
}

function withRedLetterSecurity(config) {
  let next = withNoInternetPermission(config);
  next = withAndroidHardening(next);
  next = withDataExtractionRules(next);
  next = withIosHardening(next);
  next = withAppName(next);
  return next;
}

module.exports = createRunOncePlugin(withRedLetterSecurity, 'red-letter-security', '1.0.0');
