import type { DateKey, TimeKey } from './dates';

/**
 * A marked day — a "Red Letter day". The product thesis is that most days are
 * empty, so an entry is the exception rather than the unit of everyday use.
 */
export interface Entry {
  /** Always generated by this app. Ids from imported files are never adopted. */
  id: string;
  time?: TimeKey;
  title: string;
  note?: string;
}

/**
 * Something you are waiting on someone else for. Deliberately not a task: it
 * has no due date and no completion streak, only the day you started waiting,
 * so the list answers "how long has this been sitting there".
 */
export interface WaitingItem {
  id: string;
  title: string;
  since: DateKey;
  /** Optional day to be reminded to chase it. */
  nudgeOn?: DateKey;
}

/** The whole of a user's data. Entries are keyed by local calendar day. */
export interface RedLetterData {
  schemaVersion: number;
  entries: Record<DateKey, Entry[]>;
  waiting: WaitingItem[];
}

export const SCHEMA_VERSION = 1;

export function emptyData(): RedLetterData {
  return { schemaVersion: SCHEMA_VERSION, entries: {}, waiting: [] };
}

/**
 * Hard ceilings applied to anything that comes from outside the app: restored
 * backups and imported .ics files. They exist so a malformed or hostile file
 * is refused rather than exhausting memory or locking up the UI thread.
 */
export const LIMITS = {
  /** Matches the 300-character cap the web version already enforces. */
  titleLength: 300,
  noteLength: 2_000,
  entriesPerDay: 50,
  entriesTotal: 10_000,
  waitingItems: 500,
  distinctDays: 5_000,
  /** 2 MiB. A year of marked days is a few kilobytes; anything larger is not ours. */
  importBytes: 2 * 1024 * 1024,
  /** Guards against a single pathological line in an .ics file. */
  icsLineLength: 8_192,
  icsLines: 200_000,
} as const;

/** Days ahead that a reminder may be scheduled. iOS caps pending notifications at 64. */
export const MAX_SCHEDULED_REMINDERS = 60;
